framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        missing_import_mode: strict
        excluded_patterns:
            - "**/assets/scss/_*.scss"
            - "**/assets/scss/**/_*.scss"
