framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
            - public/theme/
            - modules/Charts/Resources/assets/
        missing_import_mode: strict
        exclude_dotfiles: true
        excluded_patterns:
            - "*.md"
            - "composer.json"
            - "package.json"
