# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: "local"
            options:
                directory: "%kernel.project_dir%/public/storage"
        theme.storage:
            adapter: "local"
            options:
                directory: "%kernel.project_dir%/public/theme"
        uploads.storage:
            adapter: "local"
            options:
                directory: "%kernel.project_dir%/public/uploads"
        translations.storage:
            adapter: "local"
            options:
                directory: "%kernel.project_dir%/public/translations"
