hwi_oauth:
    # https://github.com/hwi/HWIOAuthBundle/blob/master/docs/2-configuring_resource_owners.md
    resource_owners:
        facebook:
            type: facebook
            client_id: "%env(FACEBOOK_ID)%"
            client_secret: "%env(FACEBOOK_SECRET)%"
            scope: "email public_profile"
            options:
                csrf: true
                display: popup #dialog is optimized for popup window
                auth_type: rerequest # Re-asking for Declined Permissions
        yandex:
            type: yandex
            client_id: "%env(YANDEX_ID)%"
            client_secret: "%env(YANDEX_SECRET)%"
            options:
                csrf: true
        google:
            type: google
            client_id: "%env(GOOGLE_ID)%"
            client_secret: "%env(GOOGLE_SECRET)%"
            scope: "email profile"
            options:
                access_type: offline
                csrf: true
        linkedin:
            type: linkedin
            client_id: "%env(LINKEDIN_ID)%"
            client_secret: "%env(LINKEDIN_SECRET)%"
            scope: "r_liteprofile r_emailaddress"
            options:
                csrf: true
        mailru:
            type: mailru
            client_id: "%env(MAILRU_ID)%"
            client_secret: "%env(MAILRU_SECRET)%"
            options:
                csrf: true
        odnoklassniki:
            type: odnoklassniki
            client_id: "%env(ODNOKLASSNIKI_ID)%"
            client_secret: "%env(ODNOKLASSNIKI_SECRET)%"
            options:
                application_key: "%env(ODNOKLASSNIKI_APPLICATION_KEY)%"
                csrf: true
        X-twitter:
            type: twitter
            client_id: "%env(TWITTER_CONSUMER_KEY)%"
            client_secret: "%env(TWITTER_CONSUMER_SECRET)%"
            options:
                csrf: true
        vkontakte:
            type: vkontakte
            client_id: "%env(VKONTAKTE_ID)%"
            client_secret: "%env(VKONTAKTE_SECRET)%"
            options:
                csrf: true
        github:
            type: github
            client_id: "%env(GITHUB_ID)%"
            client_secret: "%env(GITHUB_SECRET)%"
            scope: "user:email,public_repo"
            options:
                csrf: true
