security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
        Sonata\UserBundle\Model\UserInterface: "auto"

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        kyg_user_provider:
            entity:
                class: App\Modules\Users\Entity\User
                property: username
        sonata_user_bundle:
            id: sonata.user.security.user_provider

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        admin:
            lazy: true
            pattern: /admin(.*)
            provider: sonata_user_bundle
            context: user
            form_login:
                login_path: sonata_user_admin_security_login
                check_path: sonata_user_admin_security_check
                default_target_path: sonata_admin_dashboard
            logout:
                path: sonata_user_admin_security_logout
                target: sonata_user_admin_security_login
            remember_me:
                secret: "%env(APP_SECRET)%"
                lifetime: 2629746
                path: /admin
            switch_user: true
        kyg:
            lazy: true
            pattern: /kyg(.*)
            provider: kyg_user_provider
            form_login:
                login_path: kyg_login
                check_path: kyg_login
                enable_csrf: true
            logout:
                path: kyg_logout
                # where to redirect after logout
                target: kyg
            remember_me:
                signature_properties: ["password", "updatedAt"]
            login_throttling:
                max_attempts: 5
                interval: "15 minutes"

            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user: true

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_SONATA_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # Note: Only the *first* matching rule is applied
    access_control:
        # Admin login page needs to be accessed without credential
        - { path: ^/admin/login$, role: PUBLIC_ACCESS }
        - { path: ^/admin/logout$, role: PUBLIC_ACCESS }
        - { path: ^/admin/login_check$, role: PUBLIC_ACCESS }
        - { path: ^/admin/request$, role: PUBLIC_ACCESS }
        - { path: ^/admin/check-email$, role: PUBLIC_ACCESS }
        - { path: ^/admin/reset/.*$, role: PUBLIC_ACCESS }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        #- { path: ^/admin/, role: ROLE_SONATA_ADMIN }
        - { path: ^/.*, role: PUBLIC_ACCESS }

        # - { path: ^/kyg, roles: ROLE_USER }
