security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
        Sonata\UserBundle\Model\UserInterface: "auto"

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Modules\Users\Entity\User
                property: username
        sonata_user_bundle:
            id: sonata.user.security.user_provider

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        admin:
            lazy: true
            pattern: /admin(.*)
            provider: sonata_user_bundle
            context: user
            switch_user: true
            form_login:
                login_path: sonata_user_admin_security_login
                check_path: sonata_user_admin_security_check
                default_target_path: sonata_admin_dashboard
            logout:
                path: sonata_user_admin_security_logout
                target: sonata_user_admin_security_login
            remember_me:
                secret: "%env(APP_SECRET)%"
                lifetime: 2629746
                path: /admin
        main:
            lazy: true
            provider: app_user_provider
            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                    yandex: "/login/check-yandex"
                    github: "/login/check-github"
                    linkedin: "/login/check-linkedin"
                    mailru: "/login/check-mailru"
                    odnoklassniki: "/login/check-odnoklassniki"
                    X-twitter: "/login/check-x-twitter"
                    vkontakte: "/login/check-vkontakte"
                login_path: /login
                use_forward: false
                failure_path: /login

                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity
        app:
            lazy: true
            pattern: /app(.*)
            provider: app_user_provider
            entry_point: "form_login"
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                # where to redirect after logout
                target: app
            remember_me:
                secret: "%env(APP_SECRET)%"
                lifetime: 2629746
                path: app
            login_throttling:
                max_attempts: 5
                interval: "15 minutes"
            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                    yandex: "/login/check-yandex"
                    github: "/login/check-github"
                    linkedin: "/login/check-linkedin"
                    mailru: "/login/check-mailru"
                    odnoklassniki: "/login/check-odnoklassniki"
                    X-twitter: "/login/check-x-twitter"
                    vkontakte: "/login/check-vkontakte"
                login_path: /app/login
                use_forward: false
                failure_path: /app/login
                check_path: /app/login-check

                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity

            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user: true

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_SONATA_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # Note: Only the *first* matching rule is applied
    access_control:
        - { path: ^/.*, role: PUBLIC_ACCESS }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin login page needs to be accessed without credential
        - { path: ^/admin/login$, role: PUBLIC_ACCESS }
        - { path: ^/admin/logout$, role: PUBLIC_ACCESS }
        - { path: ^/admin/login_check$, role: PUBLIC_ACCESS }
        - { path: ^/admin/request$, role: PUBLIC_ACCESS }
        - { path: ^/admin/check-email$, role: PUBLIC_ACCESS }
        - { path: ^/admin/reset/.*$, role: PUBLIC_ACCESS }

        # App login page needs to be accessed without credential
        - { path: ^/app/login$, role: PUBLIC_ACCESS }
        - { path: ^/app/logout$, role: PUBLIC_ACCESS }
        - { path: ^/app/login_check$, role: PUBLIC_ACCESS }
        - { path: ^/app/request$, role: PUBLIC_ACCESS }
        - { path: ^/app/check-email$, role: PUBLIC_ACCESS }
        - { path: ^/app/verify$, role: PUBLIC_ACCESS }
        - { path: ^/app/reset/.*$, role: PUBLIC_ACCESS }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
