sonata_media:
    db_driver: doctrine_orm
    class:
        media: App\Modules\Media\Entity\SonataMediaMedia
        gallery: App\Modules\Media\Entity\SonataMediaGallery
        gallery_item: App\Modules\Media\Entity\SonataMediaGalleryItem
        category: App\Modules\Classification\Entity\SonataClassificationCategory

    force_disable_category: false # true, if you really want to disable the relation with category

    default_context: default
    admin_format: { width: 200, quality: 90, format: "jpg" }
    contexts:
        default: # the default context is mandatory
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100, quality: 70 }
                big: { width: 500, quality: 70 }
                # You can pass through any custom option to resizer by using the resizer_options key
                icon: { width: 32, quality: 70, resizer_options: { custom_crop: true } }

    cdn:
        server:
            path: /storage/media

    filesystem:
        local:
            directory: "%kernel.project_dir%/public/storage/media"
            create: false

    providers:
        file:
            service: sonata.media.provider.file
            resizer: null
            filesystem: sonata.media.filesystem.local
            cdn: sonata.media.cdn.server
            generator: sonata.media.generator.default
            thumbnail: sonata.media.thumbnail.format
            allowed_extensions: ["pdf", "txt", "rtf", "doc", "docx", "xls", "xlsx", "ppt", "pttx", "odt", "odg", "odp", "ods", "odc", "odf", "odb", "csv", "xml"]
            allowed_mime_types: ["application/pdf", "application/x-pdf", "application/rtf", "text/html", "text/rtf", "text/plain"]

        image:
            service: sonata.media.provider.image
            resizer: sonata.media.resizer.crop #sonata.media.resizer.simple sonata.media.resizer.square, sonata.media.resizer.crop
            filesystem: sonata.media.filesystem.local
            cdn: sonata.media.cdn.server
            generator: sonata.media.generator.default
            thumbnail: sonata.media.thumbnail.liip_imagine
            allowed_extensions: ["jpg", "png", "jpeg", "bmp"]
            allowed_mime_types: ["image/pjpeg", "image/jpeg", "image/png", "image/x-png", "image/bmp"]

        youtube:
            service: sonata.media.provider.youtube
            resizer: sonata.media.resizer.simple
            filesystem: sonata.media.filesystem.local
            cdn: sonata.media.cdn.server
            generator: sonata.media.generator.default
            thumbnail: sonata.media.thumbnail.liip_imagine
            html5: false

        dailymotion:
            service: sonata.media.provider.dailymotion
            resizer: sonata.media.resizer.simple
            filesystem: sonata.media.filesystem.local
            cdn: sonata.media.cdn.server
            generator: sonata.media.generator.default
            thumbnail: sonata.media.thumbnail.liip_imagine

    http:
        client: sonata.media.http.base_client # You need symfony/http-client for this
        message_factory: sonata.media.http.base_message_factory # You need nyholm/psr7 for this

    messenger:
        enabled: false
        generate_thumbnails_bus: messenger.default_bus
