sonata_media:
    class:
        media: App\Modules\Media\Entity\SonataMediaMedia
        gallery: App\Modules\Media\Entity\SonataMediaGallery
        gallery_item: App\Modules\Media\Entity\SonataMediaGalleryItem
        category: App\Modules\Classification\Entity\SonataClassificationCategory
    db_driver: doctrine_orm # or doctrine_mongodb, it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default: # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo
            formats:
                small: { width: 100, quality: 70 }
                big: { width: 500, quality: 70 }
    cdn:
        server:
            path: /storage/media
    filesystem:
        local:
            directory: "%kernel.project_dir%/public/storage/media"
            create: false
