sonata_media:
    class:
        media: App\Modules\System\Entity\SonataMediaMedia
        gallery: App\Modules\System\Entity\SonataMediaGallery
        gallery_item: App\Modules\System\Entity\SonataMediaGalleryItem
        category: App\Modules\Config\Entity\SonataClassificationCategory
    db_driver: doctrine_orm
    default_context: default
    admin_format: { width: 200, quality: 90, format: "jpg" }
    contexts:
        default:
            #download:
            #    strategy: sonata.media.security.public_strategy
            #    mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100, quality: 70 }
                big: { width: 500, quality: 70, resizer: sonata.media.resizer.crop }
                icon: { width: 32, quality: 70, resizer: sonata.media.resizer.square, resizer_options: { custom_crop: true } }

    cdn:
        server:
            path: /storage

    filesystem:
        local:
            # Directory for uploads should be writable
            directory: "%kernel.project_dir%/public/storage"
            create: false

    providers:
        image:
            thumbnail: sonata.media.thumbnail.liip_imagine
            allowed_extensions: ["jpg", "png", "gif", "jpeg", "bmp"]
            allowed_mime_types: ["image/pjpeg", "image/jpeg", "image/png", "image/x-png", "image/gif", "image/bmp"]
        #video:
        #    thumbnail: sonata.media.thumbnail.liip_imagine
        #    allowed_extensions: ["mp4", "avi", "mpeg", "mp3", "ogg", "webm"]
        #    allowed_mime_types: ["video/mp4", "video/x-msvideo", "video/mpeg", "audio/mpeg", "audio/ogg", "video/webm"]
        vimeo:
            thumbnail: sonata.media.thumbnail.liip_imagine
        youtube:
            thumbnail: sonata.media.thumbnail.liip_imagine
        dailymotion:
            thumbnail: sonata.media.thumbnail.liip_imagine
