sonata_admin:
    title: "KYG Framework"
    title_logo: bundles/KYG-framework/brand-logos/kyg-logo.png
    assets:
        extra_javascripts:
            - bundles/fosckeditor/ckeditor.js
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
