sonata_user:
    class:
        user: App\Modules\Usaer\Entity\User
    resetting:
        email:
            address: "%app.email_bot%"
            sender_name: "%app.name_bot%"
    profile:
        default_avatar: bundles/KYG-Framework/avatar/pngwing.com.png
