sonata_admin:
    assets:
        extra_stylesheets:
            - bundles/sonatatranslation/css/sonata-translation.css

sonata_block:
    blocks:
        sonata_translation.block.locale_switcher: null

sonata_translation:
    locale_switcher: true
    locales: "%kernel.enabled_locales%"
    default_locale: "%kernel.default_locale%"
    # change default behavior for translated field filtering.
    default_filter_mode: gedmo # must be either 'gedmo' or 'knplabs', default: gedmo
    # here enable the types you need
    gedmo:
        enabled: true
        # when using gedmo/doctrine-extensions, you have to register a translatable listener
        # service or if you are using a bundle that integrates the library, it will be registered
        # by the bundle (e.g. "stof_doctrine_extensions.listener.translatable" for "stof/doctrine-extensions-bundle").
        # here you can provide a custom translatable listener service name.
        translatable_listener_service: stof_doctrine_extensions.listener.translatable
    #knplabs:
    #    enabled: true
    #phpcr:
    #    enabled: true
