sonata_media:
    class:
        media: App\Modules\Media\Document\SonataMediaMedia
        gallery: App\Modules\Media\Document\SonataMediaGallery
        gallery_item: App\Modules\Media\Document\SonataMediaGalleryItem
        category: App\Modules\Classification\Entity\SonataClassificationCategory
    default_context: default
    admin_format: { width: 200, quality: 90, format: "jpg" }
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100, quality: 70 }
                big: { width: 500, quality: 70, resizer: sonata.media.resizer.crop }
                icon: { width: 32, quality: 70, resizer: sonata.media.resizer.square, resizer_options: { custom_crop: true } }

    cdn:
        server:
            path: /uploads/media

    filesystem:
        local:
            # Directory for uploads should be writable
            directory: "%kernel.project_dir%/public/uploads/media"
            create: false
