# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/doctrine-extensions/DoctrineExtensions/tree/main/doc
stof_doctrine_extensions:
    default_locale: "%kernel.default_locale%"

    uploadable:
        # Default file path: This is one of the three ways you can configure the path for the Uploadable extension
        default_file_path: "%kernel.project_dir%/public/uploads"

    orm:
        default:
            tree: true
            timestampable: true
            translatable: true
            blameable: true
            sluggable: true
            loggable: true
            ip_traceable: true
            sortable: true
            softdeleteable: true
            uploadable: true
            reference_integrity: true
