framework:
    default_locale: "%app.default_locale%"
    enabled_locales: "%app.enabled_locales%"
    translator:
        default_path: "%kernel.project_dir%/translations"
        paths:
            - "%kernel.project_dir%/public/translations"
        fallbacks: "%app.fallbacks%"
        providers:
