framework:
    default_locale: "%env(ENV_DEFAULT_LOCALE)%"
    translator:
        default_path: "%kernel.project_dir%/translations"
        paths:
            - "%kernel.project_dir%/public/translations"
        fallbacks:
            - "af"
            - "ar"
            - "az"
            - "be"
            - "bg"
            - "bs"
            - "ca"
            - "cs"
            - "cy"
            - "da"
            - "de"
            - "el"
            - "en"
            - "es"
            - "et"
            - "eu"
            - "fa"
            - "fi"
            - "fr"
            - "gl"
            - "he"
            - "hr"
            - "hu"
            - "hy"
            - "id"
            - "it"
            - "ja"
            - "lb"
            - "lt"
            - "lv"
            - "mk"
            - "mn"
            - "my"
            - "nb"
            - "nl"
            - "nn"
            - "no"
            - "pl"
            - "pt"
            - "pt_BR"
            - "ro"
            - "ru"
            - "sk"
            - "sl"
            - "sq"
            - "sr_Cyrl"
            - "sr_Latn"
            - "sv"
            - "th"
            - "tr"
            - "tl"
            - "uk"
            - "ur"
            - "uz"
            - "vi"
            - "zh_CN"
            - "zh_TW"
        providers: null
