twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"

    form_themes:
        - "form/form_theme.html.twig"
        - "@SonataMedia/Form/media_widgets.html.twig"
        - "@SonataFormatter/Form/formatter.html.twig"

    # The default path used to load templates.
    default_path: "%kernel.project_dir%/templates"

    # Pattern of file name used for cache warmer and linter.
    file_name_pattern: "*.twig"

    # The default format options used by the date filter.
    date:
        format: "%env(ENV_DATE_FORMAT)%"
        interval_format: "%d days"

        # The timezone used when formatting dates, when set to null, the timezone returned by date_default_timezone_get() is used.
        timezone: null

    # The default format options for the number_format filter.
    number_format:
        decimals: "%env(int:ENV_DECIMALS)%"
        decimal_point: "%env(ENV_DECIMAL_POINT)%"
        thousands_separator: "%env(ENV_THOUSANDS_SEPARATOR)%"
