twig:
    form_themes:
        - "bootstrap_5_layout.html.twig"
        - "form/custom_form_fields.html.twig"
        - "@SonataFormatter/Form/formatter.html.twig"
        - "@SonataMedia/Form/media_widgets.html.twig"

    globals:
        app_name: "%env(settings:twig:name)%"
        app_desktop_logo: "%env(settings:twig:desktopLogo)%"
        app_toggle_logo: "%env(settings:twig:toggleLogo)%"
        app_desktop_white: "%env(settings:twig:desktopWhite)%"
        app_toggle_white: "%env(settings:twig:toggleWhite)%"

    # The default path used to load templates.
    default_path: "%kernel.project_dir%/templates"

    # Pattern of file name used for cache warmer and linter.
    file_name_pattern: "*.twig"

    # The default format options used by the date filter.
    date:
        format: "%env(ENV_DATE_FORMAT)%"
        interval_format: "%d days"

        # The timezone used when formatting dates, when set to null, the timezone returned by date_default_timezone_get() is used.
        timezone: null

    # The default format options for the number_format filter.
    number_format:
        decimals: "%env(int:ENV_DECIMALS)%"
        decimal_point: "%env(ENV_DECIMAL_POINT)%"
        thousands_separator: "%env(ENV_THOUSANDS_SEPARATOR)%"
