twig:
    form_themes:
        - "bootstrap_5_layout.html.twig"

    # The default path used to load templates.
    default_path: "%kernel.project_dir%/templates"

    # Pattern of file name used for cache warmer and linter.
    file_name_pattern: "*.twig"
