doctrine:
    orm:
        mappings:
            Classification:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/modules/Classification/Entity"
                prefix: 'App\Modules\Classification\Entity'
                alias: Classification
