# https://github.com/jawira/doctrine-diagram-bundle
doctrine_diagram:
    er:
        filename: "%kernel.project_dir%/var/er"
        size: maxi
    class:
        filename: "%kernel.project_dir%/var/class"
        size: maxi
    convert:
        format: svg
        converter: auto
