doctrine:
    orm:
        mappings:
            System:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/modules/System/Entity"
                prefix: 'App\Modules\System\Entity'
                alias: System
