framework:
    workflows:
        user_status:
            type: "state_machine"
            marking_store:
                type: "method"
                property: "status"
            supports:
                - App\Modules\Users\Entity\User
            initial_marking: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_NEW
            places: !php/enum App\Modules\Users\Enumeration\UsersStatus
            transitions:
                validated:
                    from: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_NEW
                    to: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_VALIDATED
                pending:
                    from: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_VALIDATED
                    to: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_PENDING
                active:
                    from:
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_NEW
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_PENDING
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_INACTIVE
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_DISABLED
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_VALIDATED
                    to: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_ACTIVE
                inactive:
                    from: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_ACTIVE
                    to: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_INACTIVE
                banned:
                    from: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_ACTIVE
                    to: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_BANNED
                deleted:
                    from:
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_NEW
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_PENDING
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_ACTIVE
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_INACTIVE
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_BANNED
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_DISABLED
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_VALIDATED
                    to: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_DELETED
                disabled:
                    from:
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_NEW
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_PENDING
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_ACTIVE
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_INACTIVE
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_BANNED
                        - !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_VALIDATED
                    to: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_DISABLED
                not_banned:
                    from: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_BANNED
                    to: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_DISABLED
                not_deleted:
                    from: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_DELETED
                    to: !php/enum App\Modules\Users\Enumeration\UsersStatus::STATUS_DISABLED
