doctrine:
    orm:
        mappings:
            Nomenclature:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/modules/Nomenclature/Entity"
                prefix: 'App\Modules\Nomenclature\Entity'
                alias: Users
